// BELTRON Portal Static Data & Types

export type Language = "en" | "hi" | "bho";

export const translations = {
  en: {
    siteName: "BELTRON",
    siteFullName: "Bihar State Electronics Development Corporation Ltd.",
    tagline: "Powering Bihar's Digital Future",
    heroTitle: "Your Gateway to Digital Bihar",
    heroSubtitle:
      "Empowering citizens, businesses, and government with seamless e-governance services",
    searchPlaceholder: "Search services, tenders, careers, notifications...",
    searchBtn: "Search",
    quickLinks: "Quick Access",
    latestTenders: "Latest Tenders",
    latestCirculars: "Latest Circulars",
    careers: "Careers",
    impactMetrics: "BELTRON at a Glance",
    impactSub: "Real-time impact across Bihar's digital transformation",
    servicesTitle: "Our Services",
    servicesSub: "Comprehensive IT services for citizens, enterprises, and government",
    newsTitle: "News & Updates",
    newsSub: "Stay informed with the latest announcements",
    viewAll: "View All",
    applyNow: "Apply Now",
    download: "Download",
    lastUpdated: "Last Updated",
    forCitizens: "For Citizens",
    forVendors: "For Vendors / MSMEs",
    forDepts: "For Government Departments",
    home: "Home",
    about: "About",
    services: "Services",
    tenders: "Tenders",
    projects: "Projects",
    contact: "Contact",
    skipToContent: "Skip to Main Content",
    screenReader: "Screen Reader",
    decreaseText: "Decrease Text",
    increaseText: "Increase Text",
    highContrast: "High Contrast",
    hindi: "हिंदी",
    english: "English",
    bhojpuri: "भोजपुरी",
    govtOfBihar: "Government of Bihar",
    digitalIndia: "Digital India",
    makeInIndia: "Make in India",
    privacyPolicy: "Privacy Policy",
    disclaimer: "Disclaimer",
    sitemap: "Sitemap",
    accessibility: "Accessibility",
    terms: "Terms of Use",
    copyright: "© {year} Bihar State Electronics Development Corporation Ltd. All rights reserved.",
    lastUpdatedDate: "Last Updated: 28 May, 2026",
    websitePolicy: "Website Policy",
    contactUs: "Contact Us",
    helpDesk: "Help Desk",
    rtInfo: "RTI",
    nodal: "Nodal Officer",
    totalProjects: "Projects Delivered",
    deptsCovered: "Departments Covered",
    activeTenders: "Active Tenders",
    workforce: "Workforce Deployed",
    statesServed: "Districts Covered",
    yearsService: "Years of Service",
  },
  hi: {
    siteName: "बेल्ट्रॉन",
    siteFullName: "बिहार राज्य इलेक्ट्रॉनिक्स विकास निगम लि.",
    tagline: "बिहार के डिजिटल भविष्य को सशक्त बनाना",
    heroTitle: "डिजिटल बिहार का प्रवेश द्वार",
    heroSubtitle:
      "नागरिकों, व्यवसायों और सरकार को सुगम ई-गवर्नेंस सेवाओं से सशक्त बनाना",
    searchPlaceholder: "सेवाएं, टेंडर, करियर, अधिसूचनाएं खोजें...",
    searchBtn: "खोजें",
    quickLinks: "त्वरित पहुंच",
    latestTenders: "नवीनतम टेंडर",
    latestCirculars: "नवीनतम परिपत्र",
    careers: "करियर",
    impactMetrics: "बेल्ट्रॉन एक नज़र में",
    impactSub: "बिहार के डिजिटल परिवर्तन में वास्तविक समय प्रभाव",
    servicesTitle: "हमारी सेवाएं",
    servicesSub: "नागरिकों, उद्यमों और सरकार के लिए व्यापक आईटी सेवाएं",
    newsTitle: "समाचार एवं अपडेट",
    newsSub: "नवीनतम घोषणाओं से अवगत रहें",
    viewAll: "सभी देखें",
    applyNow: "अभी आवेदन करें",
    download: "डाउनलोड",
    lastUpdated: "अंतिम अपडेट",
    forCitizens: "नागरिकों के लिए",
    forVendors: "विक्रेताओं / MSME के लिए",
    forDepts: "सरकारी विभागों के लिए",
    home: "होम",
    about: "हमारे बारे में",
    services: "सेवाएं",
    tenders: "टेंडर",
    projects: "परियोजनाएं",
    contact: "संपर्क",
    skipToContent: "मुख्य सामग्री पर जाएं",
    screenReader: "स्क्रीन रीडर",
    decreaseText: "पाठ घटाएं",
    increaseText: "पाठ बढ़ाएं",
    highContrast: "उच्च कंट्रास्ट",
    hindi: "हिंदी",
    english: "English",
    bhojpuri: "भोजपुरी",
    govtOfBihar: "बिहार सरकार",
    digitalIndia: "डिजिटल इंडिया",
    makeInIndia: "मेक इन इंडिया",
    privacyPolicy: "गोपनीयता नीति",
    disclaimer: "अस्वीकरण",
    sitemap: "साइटमैप",
    accessibility: "अभिगम्यता",
    terms: "उपयोग की शर्तें",
    copyright: "© {year} बिहार राज्य इलेक्ट्रॉनिक्स विकास निगम लि. सर्वाधिकार सुरक्षित।",
    lastUpdatedDate: "अंतिम अपडेट: 28 मई, 2026",
    websitePolicy: "वेबसाइट नीति",
    contactUs: "हमसे संपर्क करें",
    helpDesk: "हेल्प डेस्क",
    rtInfo: "आरटीआई",
    nodal: "नोडल अधिकारी",
    totalProjects: "परियोजनाएं पूर्ण",
    deptsCovered: "विभाग शामिल",
    activeTenders: "सक्रिय टेंडर",
    workforce: "कार्यबल तैनात",
    statesServed: "जिले शामिल",
    yearsService: "सेवा के वर्ष",
  },
  bho: {
    siteName: "बेल्ट्रॉन",
    siteFullName: "बिहार राज्य इलेक्ट्रॉनिक्स विकास निगम लि.",
    tagline: "बिहार के डिजिटल भविष्य के ताकत",
    heroTitle: "डिजिटल बिहार के प्रवेश द्वार",
    heroSubtitle:
      "नागरिक, व्यापारी आ सरकार के ई-गवर्नेंस सेवा से सशक्त बनावल",
    searchPlaceholder: "सेवा, टेंडर, करियर, सूचना खोजीं...",
    searchBtn: "खोजीं",
    quickLinks: "जल्दी पहुँच",
    latestTenders: "नया टेंडर",
    latestCirculars: "नया परिपत्र",
    careers: "करियर",
    impactMetrics: "बेल्ट्रॉन एक नज़र में",
    impactSub: "बिहार के डिजिटल बदलाव में असली असर",
    servicesTitle: "हमनी के सेवा",
    servicesSub: "नागरिक, उद्यम आ सरकार खातिर पूरा आईटी सेवा",
    newsTitle: "समाचार आ अपडेट",
    newsSub: "नया घोषणा से जानकारी रखीं",
    viewAll: "सब देखीं",
    applyNow: "अभी आवेदन करीं",
    download: "डाउनलोड",
    lastUpdated: "आखिरी अपडेट",
    forCitizens: "नागरिक खातिर",
    forVendors: "विक्रेता / MSME खातिर",
    forDepts: "सरकारी विभाग खातिर",
    home: "होम",
    about: "हमनी के बारे में",
    services: "सेवा",
    tenders: "टेंडर",
    projects: "परियोजना",
    contact: "संपर्क",
    skipToContent: "मुख्य सामग्री पर जाईं",
    screenReader: "स्क्रीन रीडर",
    decreaseText: "लिखाई छोट करीं",
    increaseText: "लिखाई बड़ करीं",
    highContrast: "तेज कंट्रास्ट",
    hindi: "हिंदी",
    english: "English",
    bhojpuri: "भोजपुरी",
    govtOfBihar: "बिहार सरकार",
    digitalIndia: "डिजिटल इंडिया",
    makeInIndia: "मेक इन इंडिया",
    privacyPolicy: "गोपनीयता नीति",
    disclaimer: "अस्वीकरण",
    sitemap: "साइटमैप",
    accessibility: "अभिगम्यता",
    terms: "उपयोग के शर्त",
    copyright: "© {year} बिहार राज्य इलेक्ट्रॉनिक्स विकास निगम लि. सब अधिकार सुरक्षित।",
    lastUpdatedDate: "आखिरी अपडेट: 28 मई, 2026",
    websitePolicy: "वेबसाइट नीति",
    contactUs: "हमनी से संपर्क करीं",
    helpDesk: "हेल्प डेस्क",
    rtInfo: "आरटीआई",
    nodal: "नोडल अधिकारी",
    totalProjects: "परियोजना पूरा भइल",
    deptsCovered: "विभाग शामिल",
    activeTenders: "चालू टेंडर",
    workforce: "कार्यबल तैनात",
    statesServed: "जिला शामिल",
    yearsService: "सेवा के साल",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export const tenders = [
  {
    id: "T-2026-089",
    title: "Supply and Installation of CCTV Surveillance System for Patna Smart City",
    department: "Urban Development Dept.",
    deadline: "2026-06-15",
    value: "₹ 4.85 Cr",
    status: "open" as const,
    category: "hardware",
  },
  {
    id: "T-2026-088",
    title: "Development of Integrated Citizen Services Portal – Phase II",
    department: "IT Department, Bihar",
    deadline: "2026-06-10",
    value: "₹ 12.40 Cr",
    status: "open" as const,
    category: "software",
  },
  {
    id: "T-2026-087",
    title: "Empanelment of IT Manpower for State Data Centre Operations",
    department: "BELTRON",
    deadline: "2026-06-05",
    value: "Rate Contract",
    status: "open" as const,
    category: "manpower",
  },
  {
    id: "T-2026-086",
    title: "Annual Maintenance Contract for Network Equipment – SDC Patna",
    department: "BELTRON / IT Dept.",
    deadline: "2026-05-30",
    value: "₹ 1.20 Cr",
    status: "closing" as const,
    category: "maintenance",
  },
  {
    id: "T-2026-085",
    title: "Procurement of Laptops & Peripherals for Bihar Police Modernisation",
    department: "Home Department",
    deadline: "2026-05-28",
    value: "₹ 8.75 Cr",
    status: "closing" as const,
    category: "hardware",
  },
];

export const circulars = [
  {
    id: "C-2026-045",
    title: "Revised Guidelines for IT Vendor Empanelment – FY 2026-27",
    date: "2026-05-25",
    isNew: true,
  },
  {
    id: "C-2026-044",
    title: "Office Order: Rescheduling of Technical Committee Meeting (June 2026)",
    date: "2026-05-22",
    isNew: true,
  },
  {
    id: "C-2026-043",
    title: "Notice for Submission of Annual Performance Reports by Empanelled Agencies",
    date: "2026-05-18",
    isNew: false,
  },
  {
    id: "C-2026-042",
    title: "Corrigendum: Amendment to Tender T-2026-081 (SDC Expansion)",
    date: "2026-05-14",
    isNew: false,
  },
  {
    id: "C-2026-041",
    title: "Advisory on Data Security Compliance for State IT Infrastructure",
    date: "2026-05-10",
    isNew: false,
  },
];

export const careers = [
  {
    id: "JOB-2026-018",
    title: "Software Engineer (Java / Spring Boot)",
    qualification: "B.Tech / MCA",
    lastDate: "2026-06-20",
    posts: 25,
    isNew: true,
  },
  {
    id: "JOB-2026-017",
    title: "Project Manager – IT Infrastructure",
    qualification: "B.Tech + 7 yrs exp.",
    lastDate: "2026-06-15",
    posts: 8,
    isNew: true,
  },
  {
    id: "JOB-2026-016",
    title: "Data Entry Operator (DEO) – District Level",
    qualification: "12th Pass + Typing",
    lastDate: "2026-06-12",
    posts: 120,
    isNew: false,
  },
  {
    id: "JOB-2026-015",
    title: "Cybersecurity Analyst",
    qualification: "B.Tech / CEH / CISSP",
    lastDate: "2026-06-08",
    posts: 10,
    isNew: false,
  },
];

export const services = [
  {
    id: "s1",
    icon: "Globe",
    title: "IT Infrastructure Management",
    titleHi: "आईटी अवसंरचना प्रबंधन",
    description: "State Data Centre, network operations, cloud hosting for Bihar government departments.",
    descriptionHi: "बिहार सरकार के विभागों के लिए स्टेट डेटा सेंटर, नेटवर्क संचालन, क्लाउड होस्टिंग।",
    color: "blue",
  },
  {
    id: "s2",
    icon: "Code2",
    title: "Software Development & Integration",
    titleHi: "सॉफ्टवेयर विकास एवं एकीकरण",
    description: "Custom e-governance application development, API integrations, legacy system modernization.",
    descriptionHi: "कस्टम ई-गवर्नेंस एप्लिकेशन विकास, एपीआई एकीकरण, पुरानी प्रणाली का आधुनिकीकरण।",
    color: "indigo",
  },
  {
    id: "s3",
    icon: "Users",
    title: "IT Manpower Services",
    titleHi: "आईटी जनशक्ति सेवाएं",
    description: "Skilled IT professionals deputed to government departments across Bihar.",
    descriptionHi: "बिहार भर के सरकारी विभागों में तैनात कुशल आईटी पेशेवर।",
    color: "sky",
  },
  {
    id: "s4",
    icon: "ShieldCheck",
    title: "Cybersecurity & Audit",
    titleHi: "साइबर सुरक्षा एवं ऑडिट",
    description: "Security audits, VAPT, compliance reviews, and 24×7 SOC services.",
    descriptionHi: "सुरक्षा ऑडिट, VAPT, अनुपालन समीक्षा और 24×7 SOC सेवाएं।",
    color: "green",
  },
  {
    id: "s5",
    icon: "GraduationCap",
    title: "IT Training & Capacity Building",
    titleHi: "आईटी प्रशिक्षण एवं क्षमता निर्माण",
    description: "Training programs for government employees and citizens in digital literacy.",
    descriptionHi: "सरकारी कर्मचारियों और नागरिकों के लिए डिजिटल साक्षरता प्रशिक्षण कार्यक्रम।",
    color: "orange",
  },
  {
    id: "s6",
    icon: "Database",
    title: "e-Procurement & Tendering",
    titleHi: "ई-प्रोक्योरमेंट एवं टेंडरिंग",
    description: "End-to-end transparent procurement platform for Bihar government.",
    descriptionHi: "बिहार सरकार के लिए एंड-टू-एंड पारदर्शी खरीद प्लेटफॉर्म।",
    color: "purple",
  },
];

export const impactStats = [
  { key: "totalProjects", value: 1240, suffix: "+", icon: "Layers" },
  { key: "deptsCovered", value: 38, suffix: "", icon: "Building2" },
  { key: "activeTenders", value: 47, suffix: "", icon: "FileText" },
  { key: "workforce", value: 8500, suffix: "+", icon: "Users" },
  { key: "statesServed", value: 38, suffix: "/38", icon: "MapPin" },
  { key: "yearsService", value: 40, suffix: "+", icon: "Award" },
];

export const newsItems = [
  {
    id: "n1",
    title: "BELTRON Wins National e-Governance Award 2025 for SDC Excellence",
    titleHi: "बेल्ट्रॉन को SDC उत्कृष्टता के लिए राष्ट्रीय ई-गवर्नेंस पुरस्कार 2025",
    date: "2026-05-20",
    category: "Award",
    image: "https://images.unsplash.com/photo-1706263085333-653485333e47?w=400&q=80",
  },
  {
    id: "n2",
    title: "Launch of Bihar Digital Health Stack – Real-Time Patient Data Integration",
    titleHi: "बिहार डिजिटल हेल्थ स्टैक का शुभारंभ – रियल-टाइम रोगी डेटा एकीकरण",
    date: "2026-05-15",
    category: "Project",
    image: "https://images.unsplash.com/photo-1658724684973-8791f6bc1206?w=400&q=80",
  },
  {
    id: "n3",
    title: "MoU Signed with NIC for Enhanced State-Centre e-Governance Integration",
    titleHi: "बेहतर राज्य-केंद्र ई-गवर्नेंस एकीकरण के लिए NIC के साथ MoU",
    date: "2026-05-08",
    category: "Partnership",
    image: "https://hercules-cdn.com/file_RdKQmUc84KuLBttAusY81KYB",
  },
];

export const quickAccessLinks = [
  { label: "e-Procurement Portal", labelHi: "ई-प्रोक्योरमेंट पोर्टल", icon: "ShoppingCart", href: "#" },
  { label: "Empanelment Registration", labelHi: "एम्पेनलमेंट पंजीकरण", icon: "UserPlus", href: "#" },
  { label: "Tender Documents", labelHi: "टेंडर दस्तावेज़", icon: "FileDown", href: "/documents" },
  { label: "Track Application", labelHi: "आवेदन ट्रैक करें", icon: "Search", href: "#" },
  { label: "RTI Portal", labelHi: "आरटीआई पोर्टल", icon: "Info", href: "#" },
  { label: "Grievance Redressal", labelHi: "शिकायत निवारण", icon: "MessageSquare", href: "/grievances" },
  { label: "Project Status", labelHi: "परियोजना स्थिति", icon: "Activity", href: "#" },
  { label: "Help Desk", labelHi: "हेल्प डेस्क", icon: "Headphones", href: "#" },
];
