// Dashboard data — metrics, charts, project tracker, procurement status

export const monthlyTenderData = [
  { month: "Jun '25", published: 12, awarded: 8, value: 18.4 },
  { month: "Jul '25", published: 9,  awarded: 6, value: 11.2 },
  { month: "Aug '25", published: 15, awarded: 11, value: 24.6 },
  { month: "Sep '25", published: 11, awarded: 9, value: 16.8 },
  { month: "Oct '25", published: 18, awarded: 13, value: 31.5 },
  { month: "Nov '25", published: 14, awarded: 10, value: 22.3 },
  { month: "Dec '25", published: 7,  awarded: 5, value: 9.8 },
  { month: "Jan '26", published: 20, awarded: 15, value: 38.2 },
  { month: "Feb '26", published: 16, awarded: 12, value: 28.4 },
  { month: "Mar '26", published: 22, awarded: 16, value: 42.1 },
  { month: "Apr '26", published: 19, awarded: 14, value: 35.7 },
  { month: "May '26", published: 11, awarded: 6, value: 19.3 },
];

export const serviceDistribution = [
  { name: "IT Infrastructure", value: 34, color: "#1e4d9b" },
  { name: "Software Dev", value: 22, color: "#3b6fd4" },
  { name: "IT Manpower", value: 19, color: "#6497e8" },
  { name: "Cybersecurity", value: 11, color: "#94b8f5" },
  { name: "Training", value: 8, color: "#bbd0fa" },
  { name: "e-Procurement", value: 6, color: "#dce8fd" },
];

export const workforceByDivision = [
  { division: "IT Infra", deployed: 2400, available: 320 },
  { division: "Software", deployed: 1850, available: 210 },
  { division: "Support", deployed: 1600, available: 180 },
  { division: "Security", deployed: 820, available: 90 },
  { division: "Training", deployed: 560, available: 70 },
  { division: "Admin", deployed: 1270, available: 150 },
];

export const districtCoverage = [
  { district: "Patna", projects: 38, status: "active" },
  { district: "Gaya", projects: 22, status: "active" },
  { district: "Muzaffarpur", projects: 18, status: "active" },
  { district: "Bhagalpur", projects: 15, status: "active" },
  { district: "Darbhanga", projects: 14, status: "active" },
  { district: "Purnia", projects: 12, status: "active" },
  { district: "Samastipur", projects: 11, status: "partial" },
  { district: "Nalanda", projects: 10, status: "partial" },
];

export type ProjectStatus = "on-track" | "delayed" | "completed" | "planning";

export const projects = [
  {
    id: "P-2024-001",
    name: "Bihar State Data Centre – Phase III Expansion",
    nameHi: "बिहार राज्य डेटा सेंटर – चरण III विस्तार",
    department: "BELTRON",
    startDate: "2024-04-01",
    endDate: "2026-09-30",
    progress: 68,
    status: "on-track" as ProjectStatus,
    budget: "₹ 85.40 Cr",
    spent: "₹ 58.07 Cr",
    milestones: [
      { label: "Foundation & Civil Work", done: true },
      { label: "Power & Cooling Infrastructure", done: true },
      { label: "Network Cabling & Racks", done: true },
      { label: "Server Installation", done: false },
      { label: "Commissioning & Testing", done: false },
    ],
  },
  {
    id: "P-2024-002",
    name: "CM Dashboard – Real-Time Governance Analytics",
    nameHi: "CM डैशबोर्ड – रीयल-टाइम गवर्नेंस एनालिटिक्स",
    department: "Cabinet Secretariat",
    startDate: "2024-07-01",
    endDate: "2026-06-30",
    progress: 82,
    status: "on-track" as ProjectStatus,
    budget: "₹ 12.80 Cr",
    spent: "₹ 10.50 Cr",
    milestones: [
      { label: "Data Source Integration (38 depts)", done: true },
      { label: "Dashboard UI Development", done: true },
      { label: "AI Analytics Module", done: true },
      { label: "UAT & Training", done: false },
      { label: "Go-Live", done: false },
    ],
  },
  {
    id: "P-2025-003",
    name: "e-District 2.0 – Unified Service Delivery Platform",
    nameHi: "ई-जिला 2.0 – एकीकृत सेवा वितरण मंच",
    department: "General Admin Dept.",
    startDate: "2025-01-15",
    endDate: "2026-12-31",
    progress: 45,
    status: "delayed" as ProjectStatus,
    budget: "₹ 32.60 Cr",
    spent: "₹ 14.67 Cr",
    milestones: [
      { label: "Requirements & SRS Finalization", done: true },
      { label: "Backend API Development", done: true },
      { label: "Frontend Development", done: false },
      { label: "District Office Integration", done: false },
      { label: "Go-Live Phase 1 (10 districts)", done: false },
    ],
  },
  {
    id: "P-2025-004",
    name: "Bihar Police CCTNS Modernisation",
    nameHi: "बिहार पुलिस CCTNS आधुनिकीकरण",
    department: "Home Department",
    startDate: "2025-03-01",
    endDate: "2026-08-31",
    progress: 55,
    status: "on-track" as ProjectStatus,
    budget: "₹ 18.90 Cr",
    spent: "₹ 10.40 Cr",
    milestones: [
      { label: "Hardware Procurement", done: true },
      { label: "Network Setup – 50 Police Stations", done: true },
      { label: "CCTNS Software Deployment", done: false },
      { label: "Staff Training", done: false },
      { label: "Data Migration", done: false },
    ],
  },
  {
    id: "P-2023-005",
    name: "Bihar Integrated Health Management System",
    nameHi: "बिहार एकीकृत स्वास्थ्य प्रबंधन प्रणाली",
    department: "Health Department",
    startDate: "2023-06-01",
    endDate: "2025-12-31",
    progress: 100,
    status: "completed" as ProjectStatus,
    budget: "₹ 28.40 Cr",
    spent: "₹ 27.92 Cr",
    milestones: [
      { label: "System Design & Architecture", done: true },
      { label: "Hospital Management Module", done: true },
      { label: "Patient Record Integration", done: true },
      { label: "Training & Rollout (800+ facilities)", done: true },
      { label: "Go-Live & Handover", done: true },
    ],
  },
  {
    id: "P-2026-006",
    name: "Bihar AI Centre of Excellence – Phase 1",
    nameHi: "बिहार AI सेंटर ऑफ एक्सीलेंस – चरण 1",
    department: "Science & Technology Dept.",
    startDate: "2026-06-01",
    endDate: "2027-05-31",
    progress: 5,
    status: "planning" as ProjectStatus,
    budget: "₹ 22.00 Cr",
    spent: "₹ 1.10 Cr",
    milestones: [
      { label: "Site Identification & MoU", done: true },
      { label: "Infrastructure Design", done: false },
      { label: "GPU Cluster Procurement", done: false },
      { label: "Research Partnership Agreements", done: false },
      { label: "Centre Inauguration", done: false },
    ],
  },
];

export const procurementOrders = [
  {
    id: "PO-2026-0412",
    vendor: "TechServe Solutions Pvt Ltd",
    item: "Enterprise Servers – Dell PowerEdge R750",
    qty: "24 Units",
    orderDate: "2026-04-10",
    deliveryDue: "2026-05-25",
    status: "delivered" as const,
    value: "₹ 1.84 Cr",
    department: "BELTRON / SDC",
  },
  {
    id: "PO-2026-0398",
    vendor: "CyberShield Technologies",
    item: "Firewall Appliances – Fortinet 600F",
    qty: "8 Units",
    orderDate: "2026-04-01",
    deliveryDue: "2026-06-01",
    status: "in-transit" as const,
    value: "₹ 68.40 Lakh",
    department: "BELTRON / IT Dept.",
  },
  {
    id: "PO-2026-0381",
    vendor: "DataLink Infra Pvt Ltd",
    item: "Structured Cabling – CAT6A (SDC Phase III)",
    qty: "12,000 mtr",
    orderDate: "2026-03-20",
    deliveryDue: "2026-05-30",
    status: "delayed" as const,
    value: "₹ 42.60 Lakh",
    department: "BELTRON",
  },
  {
    id: "PO-2026-0365",
    vendor: "BroadConnect IT Services",
    item: "Annual Software Licenses – Microsoft EA",
    qty: "5,000 Seats",
    orderDate: "2026-03-10",
    deliveryDue: "2026-04-10",
    status: "delivered" as const,
    value: "₹ 3.20 Cr",
    department: "Multiple Depts.",
  },
  {
    id: "PO-2026-0350",
    vendor: "SecureNet India Ltd",
    item: "CCTV Cameras – IP 4K Vandal-Proof",
    qty: "850 Units",
    orderDate: "2026-03-01",
    deliveryDue: "2026-06-15",
    status: "processing" as const,
    value: "₹ 1.28 Cr",
    department: "Urban Dev. Dept.",
  },
];
