// Document Download Center data

export type DocumentCategory = "Annual Report" | "Form" | "Circular" | "Policy" | "Manual" | "Tender Document";

export type DocumentItem = {
  id: string;
  title: string;
  titleHi: string;
  category: DocumentCategory;
  department: string;
  year: number;
  fileSize: string;
  fileType: "PDF" | "XLSX" | "DOCX" | "ZIP";
  publishedDate: string;
  downloads: number;
  description: string;
  descriptionHi: string;
};

export const documentCategories: DocumentCategory[] = [
  "Annual Report",
  "Form",
  "Circular",
  "Policy",
  "Manual",
  "Tender Document",
];

export const documentDepartments = [
  "BELTRON",
  "IT Department",
  "Urban Development",
  "Home Department",
  "Science & Technology",
  "Education Department",
  "Health Department",
  "Revenue & Land",
];

export const documentYears = [2026, 2025, 2024, 2023, 2022, 2021];

export const allDocuments: DocumentItem[] = [
  {
    id: "DOC-001",
    title: "BELTRON Annual Report 2025-26",
    titleHi: "बेल्ट्रॉन वार्षिक रिपोर्ट 2025-26",
    category: "Annual Report",
    department: "BELTRON",
    year: 2026,
    fileSize: "4.2 MB",
    fileType: "PDF",
    publishedDate: "2026-04-15",
    downloads: 1245,
    description: "Comprehensive annual report covering financial performance, project milestones, human resources, and strategic roadmap for FY 2025-26.",
    descriptionHi: "वित्तीय प्रदर्शन, परियोजना मील के पत्थर, मानव संसाधन और वित्त वर्ष 2025-26 के लिए रणनीतिक रोडमैप को कवर करने वाली व्यापक वार्षिक रिपोर्ट।",
  },
  {
    id: "DOC-002",
    title: "BELTRON Annual Report 2024-25",
    titleHi: "बेल्ट्रॉन वार्षिक रिपोर्ट 2024-25",
    category: "Annual Report",
    department: "BELTRON",
    year: 2025,
    fileSize: "3.8 MB",
    fileType: "PDF",
    publishedDate: "2025-04-20",
    downloads: 3420,
    description: "Annual report for FY 2024-25 including audited financial statements, project completion data, and workforce statistics.",
    descriptionHi: "ऑडिटेड वित्तीय विवरण, परियोजना पूर्णता डेटा और कार्यबल सांख्यिकी सहित वित्त वर्ष 2024-25 की वार्षिक रिपोर्ट।",
  },
  {
    id: "DOC-003",
    title: "BELTRON Annual Report 2023-24",
    titleHi: "बेल्ट्रॉन वार्षिक रिपोर्ट 2023-24",
    category: "Annual Report",
    department: "BELTRON",
    year: 2024,
    fileSize: "3.5 MB",
    fileType: "PDF",
    publishedDate: "2024-04-18",
    downloads: 5102,
    description: "Annual performance report for FY 2023-24 with details on e-governance implementations and state-wide IT infrastructure growth.",
    descriptionHi: "ई-गवर्नेंस कार्यान्वयन और राज्यव्यापी आईटी अवसंरचना विकास के विवरण के साथ वित्त वर्ष 2023-24 की वार्षिक प्रदर्शन रिपोर्ट।",
  },
  {
    id: "DOC-004",
    title: "Vendor Empanelment Application Form (FY 2026-27)",
    titleHi: "विक्रेता एम्पेनलमेंट आवेदन फॉर्म (वित्त वर्ष 2026-27)",
    category: "Form",
    department: "BELTRON",
    year: 2026,
    fileSize: "520 KB",
    fileType: "PDF",
    publishedDate: "2026-05-01",
    downloads: 892,
    description: "Standard application form for IT vendor empanelment with BELTRON. Includes self-declaration, technical capability, and financial eligibility annexures.",
    descriptionHi: "बेल्ट्रॉन के साथ आईटी विक्रेता एम्पेनलमेंट के लिए मानक आवेदन फॉर्म। स्व-घोषणा, तकनीकी क्षमता और वित्तीय पात्रता अनुलग्नक शामिल हैं।",
  },
  {
    id: "DOC-005",
    title: "IT Manpower Requisition Form",
    titleHi: "आईटी जनशक्ति मांगपत्र फॉर्म",
    category: "Form",
    department: "IT Department",
    year: 2026,
    fileSize: "180 KB",
    fileType: "DOCX",
    publishedDate: "2026-03-15",
    downloads: 654,
    description: "Requisition form for government departments to request IT professionals through BELTRON manpower services.",
    descriptionHi: "सरकारी विभागों के लिए बेल्ट्रॉन जनशक्ति सेवाओं के माध्यम से आईटी पेशेवरों की मांग करने का फॉर्म।",
  },
  {
    id: "DOC-006",
    title: "RTI Application Form – BELTRON",
    titleHi: "RTI आवेदन फॉर्म – बेल्ट्रॉन",
    category: "Form",
    department: "BELTRON",
    year: 2026,
    fileSize: "95 KB",
    fileType: "PDF",
    publishedDate: "2026-01-10",
    downloads: 2130,
    description: "Right to Information application form as per RTI Act 2005. Submit to the designated Public Information Officer, BELTRON.",
    descriptionHi: "RTI अधिनियम 2005 के अनुसार सूचना का अधिकार आवेदन पत्र। बेल्ट्रॉन के निर्दिष्ट जन सूचना अधिकारी को जमा करें।",
  },
  {
    id: "DOC-007",
    title: "Data Security & Privacy Policy (v3.2)",
    titleHi: "डेटा सुरक्षा और गोपनीयता नीति (v3.2)",
    category: "Policy",
    department: "IT Department",
    year: 2026,
    fileSize: "1.1 MB",
    fileType: "PDF",
    publishedDate: "2026-02-28",
    downloads: 980,
    description: "Comprehensive data security and privacy policy applicable to all BELTRON-managed IT systems and state government portals.",
    descriptionHi: "सभी बेल्ट्रॉन-प्रबंधित आईटी प्रणालियों और राज्य सरकार पोर्टलों पर लागू व्यापक डेटा सुरक्षा और गोपनीयता नीति।",
  },
  {
    id: "DOC-008",
    title: "IT Procurement Policy – Bihar State (2025 Revision)",
    titleHi: "आईटी प्रोक्योरमेंट नीति – बिहार राज्य (2025 संशोधन)",
    category: "Policy",
    department: "IT Department",
    year: 2025,
    fileSize: "2.4 MB",
    fileType: "PDF",
    publishedDate: "2025-08-15",
    downloads: 1876,
    description: "Revised IT procurement policy for all Bihar government departments including rate contract guidelines, GeM integration, and vendor selection criteria.",
    descriptionHi: "दर अनुबंध दिशानिर्देश, GeM एकीकरण और विक्रेता चयन मानदंड सहित सभी बिहार सरकार विभागों के लिए संशोधित आईटी प्रोक्योरमेंट नीति।",
  },
  {
    id: "DOC-009",
    title: "Cloud Adoption Framework for Bihar Government",
    titleHi: "बिहार सरकार के लिए क्लाउड अपनाने की रूपरेखा",
    category: "Policy",
    department: "Science & Technology",
    year: 2025,
    fileSize: "3.1 MB",
    fileType: "PDF",
    publishedDate: "2025-06-20",
    downloads: 756,
    description: "Framework document for cloud migration of government applications including MeitY cloud guidelines compliance and hybrid cloud strategy.",
    descriptionHi: "MeitY क्लाउड दिशानिर्देशों के अनुपालन और हाइब्रिड क्लाउड रणनीति सहित सरकारी अनुप्रयोगों के क्लाउड माइग्रेशन के लिए फ्रेमवर्क दस्तावेज़।",
  },
  {
    id: "DOC-010",
    title: "e-Governance Application Development Manual",
    titleHi: "ई-गवर्नेंस एप्लिकेशन विकास मैनुअल",
    category: "Manual",
    department: "BELTRON",
    year: 2025,
    fileSize: "5.6 MB",
    fileType: "PDF",
    publishedDate: "2025-09-10",
    downloads: 1432,
    description: "Technical manual covering coding standards, architecture patterns, security guidelines, and testing requirements for all BELTRON e-governance projects.",
    descriptionHi: "सभी बेल्ट्रॉन ई-गवर्नेंस परियोजनाओं के लिए कोडिंग मानक, आर्किटेक्चर पैटर्न, सुरक्षा दिशानिर्देश और परीक्षण आवश्यकताओं को कवर करने वाला तकनीकी मैनुअल।",
  },
  {
    id: "DOC-011",
    title: "State Data Centre Operations Manual (v2.0)",
    titleHi: "स्टेट डेटा सेंटर संचालन मैनुअल (v2.0)",
    category: "Manual",
    department: "BELTRON",
    year: 2025,
    fileSize: "4.8 MB",
    fileType: "PDF",
    publishedDate: "2025-07-01",
    downloads: 645,
    description: "Operations and maintenance manual for Bihar State Data Centre covering infrastructure management, incident response, SLA monitoring, and DR procedures.",
    descriptionHi: "बिहार स्टेट डेटा सेंटर के लिए संचालन और रखरखाव मैनुअल जिसमें अवसंरचना प्रबंधन, घटना प्रतिक्रिया, SLA निगरानी और DR प्रक्रियाएं शामिल हैं।",
  },
  {
    id: "DOC-012",
    title: "BSWANN Network User Manual",
    titleHi: "BSWANN नेटवर्क उपयोगकर्ता मैनुअल",
    category: "Manual",
    department: "IT Department",
    year: 2024,
    fileSize: "2.9 MB",
    fileType: "PDF",
    publishedDate: "2024-11-15",
    downloads: 890,
    description: "User manual for Bihar State Wide Area Network (BSWANN) connectivity, VPN setup, bandwidth management, and troubleshooting guide.",
    descriptionHi: "बिहार राज्य व्यापक क्षेत्र नेटवर्क (BSWANN) कनेक्टिविटी, VPN सेटअप, बैंडविड्थ प्रबंधन और समस्या निवारण गाइड के लिए उपयोगकर्ता मैनुअल।",
  },
  {
    id: "DOC-013",
    title: "Revised Circular: IT Asset Disposal Guidelines",
    titleHi: "संशोधित परिपत्र: आईटी संपत्ति निपटान दिशानिर्देश",
    category: "Circular",
    department: "BELTRON",
    year: 2026,
    fileSize: "340 KB",
    fileType: "PDF",
    publishedDate: "2026-04-10",
    downloads: 412,
    description: "Updated guidelines for environmentally responsible disposal of IT assets including e-waste management and data destruction procedures.",
    descriptionHi: "ई-कचरा प्रबंधन और डेटा विनाश प्रक्रियाओं सहित आईटी संपत्तियों के पर्यावरण-जिम्मेदार निपटान के लिए अद्यतन दिशानिर्देश।",
  },
  {
    id: "DOC-014",
    title: "Circular: Mandatory GIGW Compliance for All State Portals",
    titleHi: "परिपत्र: सभी राज्य पोर्टलों के लिए अनिवार्य GIGW अनुपालन",
    category: "Circular",
    department: "IT Department",
    year: 2025,
    fileSize: "280 KB",
    fileType: "PDF",
    publishedDate: "2025-12-01",
    downloads: 1560,
    description: "Directive for mandatory GIGW 3.0 compliance for all existing and new Bihar government portals with compliance deadline.",
    descriptionHi: "सभी मौजूदा और नए बिहार सरकार पोर्टलों के लिए अनुपालन समय सीमा के साथ अनिवार्य GIGW 3.0 अनुपालन के लिए निर्देश।",
  },
  {
    id: "DOC-015",
    title: "NIT Template for IT Hardware Procurement",
    titleHi: "आईटी हार्डवेयर प्रोक्योरमेंट के लिए NIT टेम्पलेट",
    category: "Tender Document",
    department: "BELTRON",
    year: 2026,
    fileSize: "750 KB",
    fileType: "DOCX",
    publishedDate: "2026-01-20",
    downloads: 1023,
    description: "Standard Notice Inviting Tender template for IT hardware procurement following GFR 2017 and Bihar Finance Rules.",
    descriptionHi: "GFR 2017 और बिहार वित्त नियमों का पालन करते हुए आईटी हार्डवेयर प्रोक्योरमेंट के लिए मानक निविदा आमंत्रण सूचना टेम्पलेट।",
  },
  {
    id: "DOC-016",
    title: "RFP Template for Software Development Projects",
    titleHi: "सॉफ्टवेयर विकास परियोजनाओं के लिए RFP टेम्पलेट",
    category: "Tender Document",
    department: "BELTRON",
    year: 2025,
    fileSize: "1.8 MB",
    fileType: "DOCX",
    publishedDate: "2025-10-05",
    downloads: 2340,
    description: "Standard RFP template for software development projects including technical evaluation matrix, SLA framework, and commercial bid format.",
    descriptionHi: "तकनीकी मूल्यांकन मैट्रिक्स, SLA फ्रेमवर्क और वाणिज्यिक बोली प्रारूप सहित सॉफ्टवेयर विकास परियोजनाओं के लिए मानक RFP टेम्पलेट।",
  },
  {
    id: "DOC-017",
    title: "Grievance Redressal Mechanism – BELTRON",
    titleHi: "शिकायत निवारण तंत्र – बेल्ट्रॉन",
    category: "Policy",
    department: "BELTRON",
    year: 2024,
    fileSize: "680 KB",
    fileType: "PDF",
    publishedDate: "2024-06-15",
    downloads: 1890,
    description: "Detailed procedure for citizen and vendor grievance submission, escalation matrix, timelines, and resolution process.",
    descriptionHi: "नागरिक और विक्रेता शिकायत प्रस्तुत करने, एस्केलेशन मैट्रिक्स, समयसीमा और समाधान प्रक्रिया की विस्तृत प्रक्रिया।",
  },
  {
    id: "DOC-018",
    title: "Employee Service Book Format",
    titleHi: "कर्मचारी सेवा पुस्तक प्रारूप",
    category: "Form",
    department: "BELTRON",
    year: 2024,
    fileSize: "420 KB",
    fileType: "PDF",
    publishedDate: "2024-03-01",
    downloads: 567,
    description: "Standard service book format for BELTRON employees recording service history, leave records, and annual increments.",
    descriptionHi: "सेवा इतिहास, अवकाश रिकॉर्ड और वार्षिक वेतन वृद्धि दर्ज करने के लिए बेल्ट्रॉन कर्मचारियों के लिए मानक सेवा पुस्तक प्रारूप।",
  },
  {
    id: "DOC-019",
    title: "Cybersecurity Incident Response Plan",
    titleHi: "साइबर सुरक्षा घटना प्रतिक्रिया योजना",
    category: "Manual",
    department: "IT Department",
    year: 2026,
    fileSize: "2.1 MB",
    fileType: "PDF",
    publishedDate: "2026-01-05",
    downloads: 723,
    description: "Standard Operating Procedures for cybersecurity incident detection, containment, eradication, and recovery for state IT infrastructure.",
    descriptionHi: "राज्य आईटी अवसंरचना के लिए साइबर सुरक्षा घटना का पता लगाने, नियंत्रण, उन्मूलन और पुनर्प्राप्ति के लिए मानक संचालन प्रक्रियाएं।",
  },
  {
    id: "DOC-020",
    title: "Bihar IT Policy 2024 (Full Document)",
    titleHi: "बिहार आईटी नीति 2024 (पूर्ण दस्तावेज़)",
    category: "Policy",
    department: "IT Department",
    year: 2024,
    fileSize: "6.2 MB",
    fileType: "PDF",
    publishedDate: "2024-01-26",
    downloads: 4520,
    description: "Complete Bihar Information Technology Policy 2024 covering digital governance, startup ecosystem, IT education, and investment incentives.",
    descriptionHi: "डिजिटल गवर्नेंस, स्टार्टअप इकोसिस्टम, आईटी शिक्षा और निवेश प्रोत्साहन को कवर करने वाली पूर्ण बिहार सूचना प्रौद्योगिकी नीति 2024।",
  },
];
