// Extended data for portal pages

export const tenderCategories = ["All", "Hardware", "Software", "Manpower", "Maintenance", "Consulting"] as const;
export type TenderCategory = (typeof tenderCategories)[number];

export const tenderStatuses = ["All", "Open", "Closing Soon", "Closed", "Awarded"] as const;
export type TenderStatus = (typeof tenderStatuses)[number];

export const allTenders = [
  {
    id: "T-2026-089",
    title: "Supply and Installation of CCTV Surveillance System for Patna Smart City",
    titleHi: "पटना स्मार्ट सिटी के लिए CCTV सर्विलांस सिस्टम की आपूर्ति और स्थापना",
    department: "Urban Development Dept.",
    deadline: "2026-06-15",
    publishedOn: "2026-05-01",
    value: "₹ 4.85 Cr",
    status: "open" as const,
    category: "Hardware",
    refNo: "UDD/BELTRON/2026/089",
    description:
      "Supply, installation, testing & commissioning of IP-based CCTV surveillance system including cameras, NVR, storage, and control room equipment for Patna Smart City project.",
    docs: ["NIT_T2026089.pdf", "Technical_Specs_T2026089.pdf", "BOQ_T2026089.xlsx"],
    bidSecurity: "₹ 9.70 Lakh",
    prequalification: true,
  },
  {
    id: "T-2026-088",
    title: "Development of Integrated Citizen Services Portal – Phase II",
    titleHi: "एकीकृत नागरिक सेवा पोर्टल का विकास – चरण II",
    department: "IT Department, Bihar",
    deadline: "2026-06-10",
    publishedOn: "2026-04-28",
    value: "₹ 12.40 Cr",
    status: "open" as const,
    category: "Software",
    refNo: "ITD/BELTRON/2026/088",
    description:
      "Design, development, deployment and maintenance of Phase II of the Integrated Citizen Services Portal covering 15 additional government departments and mobile app development.",
    docs: ["RFP_T2026088.pdf", "Draft_SLA_T2026088.pdf", "Technical_RFP_T2026088.pdf"],
    bidSecurity: "₹ 24.80 Lakh",
    prequalification: true,
  },
  {
    id: "T-2026-087",
    title: "Empanelment of IT Manpower for State Data Centre Operations",
    titleHi: "स्टेट डेटा सेंटर संचालन के लिए आईटी जनशक्ति का एम्पेनलमेंट",
    department: "BELTRON",
    deadline: "2026-06-05",
    publishedOn: "2026-04-25",
    value: "Rate Contract",
    status: "open" as const,
    category: "Manpower",
    refNo: "BELTRON/SDC/2026/087",
    description:
      "Empanelment of IT manpower agencies for deputing skilled professionals (Network Engineers, System Admins, DBAs, Security Analysts) at Bihar State Data Centre, Patna.",
    docs: ["Empanelment_Notice_T2026087.pdf", "Eligibility_Criteria_T2026087.pdf"],
    bidSecurity: "N/A",
    prequalification: false,
  },
  {
    id: "T-2026-086",
    title: "Annual Maintenance Contract for Network Equipment – SDC Patna",
    titleHi: "SDC पटना के लिए नेटवर्क उपकरण का वार्षिक रखरखाव अनुबंध",
    department: "BELTRON / IT Dept.",
    deadline: "2026-05-30",
    publishedOn: "2026-04-20",
    value: "₹ 1.20 Cr",
    status: "closing" as const,
    category: "Maintenance",
    refNo: "BELTRON/AMC/2026/086",
    description:
      "Annual Maintenance Contract for network equipment including routers, switches, firewalls, and load balancers deployed at Bihar State Data Centre, Patna.",
    docs: ["NIT_T2026086.pdf", "Equipment_List_T2026086.xlsx"],
    bidSecurity: "₹ 2.40 Lakh",
    prequalification: false,
  },
  {
    id: "T-2026-085",
    title: "Procurement of Laptops & Peripherals for Bihar Police Modernisation",
    titleHi: "बिहार पुलिस आधुनिकीकरण के लिए लैपटॉप और परिधीय उपकरणों की खरीद",
    department: "Home Department",
    deadline: "2026-05-28",
    publishedOn: "2026-04-15",
    value: "₹ 8.75 Cr",
    status: "closing" as const,
    category: "Hardware",
    refNo: "HD/BELTRON/2026/085",
    description:
      "Procurement of 2,500 laptops with peripherals (mouse, keyboard, bag) for Bihar Police modernisation programme under MHA grant.",
    docs: ["GeM_Tender_T2026085.pdf", "Tech_Specs_T2026085.pdf"],
    bidSecurity: "₹ 17.50 Lakh",
    prequalification: false,
  },
  {
    id: "T-2026-084",
    title: "Consulting Services for Bihar AI/ML Centre of Excellence",
    titleHi: "बिहार AI/ML सेंटर ऑफ एक्सीलेंस के लिए परामर्श सेवाएं",
    department: "Science & Technology Dept.",
    deadline: "2026-05-20",
    publishedOn: "2026-04-10",
    value: "₹ 3.50 Cr",
    status: "closed" as const,
    category: "Consulting",
    refNo: "STD/BELTRON/2026/084",
    description:
      "Consulting services for establishing Bihar AI/ML Centre of Excellence including technology roadmap, infrastructure design, and capacity building.",
    docs: ["EOI_T2026084.pdf"],
    bidSecurity: "₹ 7.00 Lakh",
    prequalification: true,
  },
  {
    id: "T-2026-083",
    title: "Supply of Servers and Storage for e-District Data Centre Expansion",
    titleHi: "ई-जिला डेटा सेंटर विस्तार के लिए सर्वर और स्टोरेज की आपूर्ति",
    department: "BELTRON",
    deadline: "2026-05-10",
    publishedOn: "2026-04-01",
    value: "₹ 6.20 Cr",
    status: "awarded" as const,
    category: "Hardware",
    refNo: "BELTRON/HW/2026/083",
    description:
      "Procurement of enterprise-grade servers, SAN storage, and related hardware for expansion of e-District Data Centre infrastructure.",
    docs: ["NIT_T2026083.pdf", "Award_Letter_T2026083.pdf"],
    bidSecurity: "₹ 12.40 Lakh",
    prequalification: false,
  },
];

export const allCirculars = [
  {
    id: "C-2026-045",
    title: "Revised Guidelines for IT Vendor Empanelment – FY 2026-27",
    titleHi: "आईटी विक्रेता एम्पेनलमेंट के लिए संशोधित दिशानिर्देश – वित्त वर्ष 2026-27",
    date: "2026-05-25",
    category: "Policy",
    isNew: true,
    doc: "Circular_C2026045.pdf",
    summary: "The empanelment process has been revised with stricter turnover and CMMI certification requirements for Tier-1 vendors.",
  },
  {
    id: "C-2026-044",
    title: "Office Order: Rescheduling of Technical Committee Meeting (June 2026)",
    titleHi: "कार्यालय आदेश: तकनीकी समिति बैठक का पुनर्निर्धारण (जून 2026)",
    date: "2026-05-22",
    category: "Office Order",
    isNew: true,
    doc: "OO_C2026044.pdf",
    summary: "The Technical Committee meeting scheduled for 15 June 2026 has been rescheduled to 22 June 2026 at 11:00 AM, BELTRON Bhawan, Patna.",
  },
  {
    id: "C-2026-043",
    title: "Notice for Submission of Annual Performance Reports by Empanelled Agencies",
    titleHi: "एम्पेनल्ड एजेंसियों द्वारा वार्षिक प्रदर्शन रिपोर्ट जमा करने की सूचना",
    date: "2026-05-18",
    category: "Notice",
    isNew: false,
    doc: "Notice_C2026043.pdf",
    summary: "All empanelled IT agencies are required to submit their Annual Performance Report for FY 2025-26 by 30 June 2026.",
  },
  {
    id: "C-2026-042",
    title: "Corrigendum: Amendment to Tender T-2026-081 (SDC Expansion)",
    titleHi: "शुद्धिपत्र: टेंडर T-2026-081 (SDC विस्तार) में संशोधन",
    date: "2026-05-14",
    category: "Corrigendum",
    isNew: false,
    doc: "Corrigendum_C2026042.pdf",
    summary: "Amendment to eligibility criteria in Clause 4.2 — minimum annual turnover reduced from ₹25 Cr to ₹15 Cr.",
  },
  {
    id: "C-2026-041",
    title: "Advisory on Data Security Compliance for State IT Infrastructure",
    titleHi: "राज्य आईटी अवसंरचना के लिए डेटा सुरक्षा अनुपालन पर एडवाइजरी",
    date: "2026-05-10",
    category: "Advisory",
    isNew: false,
    doc: "Advisory_C2026041.pdf",
    summary: "All departments using BELTRON-managed infrastructure must complete the ISO 27001 compliance audit by 31 August 2026.",
  },
  {
    id: "C-2026-040",
    title: "Notification: BELTRON Board Meeting Minutes – April 2026",
    titleHi: "अधिसूचना: बेल्ट्रॉन बोर्ड बैठक कार्यवृत्त – अप्रैल 2026",
    date: "2026-05-05",
    category: "Notification",
    isNew: false,
    doc: "BoardMinutes_C2026040.pdf",
    summary: "Minutes of the 124th Board of Directors meeting held on 28 April 2026 are now available for reference.",
  },
];

export const allJobs = [
  {
    id: "JOB-2026-018",
    title: "Software Engineer (Java / Spring Boot)",
    titleHi: "सॉफ्टवेयर इंजीनियर (Java / Spring Boot)",
    qualification: "B.Tech / MCA",
    experience: "2-5 years",
    lastDate: "2026-06-20",
    posts: 25,
    location: "Patna",
    salary: "₹ 40,000 – 65,000 / month",
    isNew: true,
    category: "Technical",
    description:
      "Development of e-governance applications using Java, Spring Boot, REST APIs, and microservices architecture. Must have experience with Angular/React frontend.",
    eligibility: ["B.Tech (CS/IT/ECE) or MCA from recognized university", "Minimum 2 years of Java/Spring Boot experience", "Knowledge of Git, Docker, and CI/CD pipelines"],
    doc: "Notification_JOB2026018.pdf",
  },
  {
    id: "JOB-2026-017",
    title: "Project Manager – IT Infrastructure",
    titleHi: "प्रोजेक्ट मैनेजर – आईटी इन्फ्रास्ट्रक्चर",
    qualification: "B.Tech + 7 yrs exp.",
    experience: "7+ years",
    lastDate: "2026-06-15",
    posts: 8,
    location: "Patna",
    salary: "₹ 80,000 – 1,20,000 / month",
    isNew: true,
    category: "Management",
    description:
      "Lead IT infrastructure projects including data centre operations, network expansion, and cloud migration for Bihar government departments.",
    eligibility: ["B.Tech (CS/IT) with 7+ years experience", "PMP / Prince2 certification preferred", "Prior e-governance project experience mandatory"],
    doc: "Notification_JOB2026017.pdf",
  },
  {
    id: "JOB-2026-016",
    title: "Data Entry Operator (DEO) – District Level",
    titleHi: "डेटा एंट्री ऑपरेटर (DEO) – जिला स्तर",
    qualification: "12th Pass + Typing",
    experience: "Fresher",
    lastDate: "2026-06-12",
    posts: 120,
    location: "All 38 Districts",
    salary: "₹ 12,000 – 18,000 / month",
    isNew: false,
    category: "Support",
    description:
      "Data entry and record management at district government offices. Must have typing speed of minimum 35 WPM (English) and 20 WPM (Hindi).",
    eligibility: ["12th pass from recognized board", "Typing speed 35 WPM English / 20 WPM Hindi", "Basic computer knowledge (MS Office, internet)"],
    doc: "Notification_JOB2026016.pdf",
  },
  {
    id: "JOB-2026-015",
    title: "Cybersecurity Analyst",
    titleHi: "साइबर सुरक्षा विश्लेषक",
    qualification: "B.Tech / CEH / CISSP",
    experience: "3-6 years",
    lastDate: "2026-06-08",
    posts: 10,
    location: "Patna (SDC)",
    salary: "₹ 55,000 – 90,000 / month",
    isNew: false,
    category: "Technical",
    description:
      "Monitor and protect Bihar State Data Centre infrastructure from cyber threats. Conduct VAPT, security audits, and incident response.",
    eligibility: ["B.Tech (CS/IT) with 3+ years in cybersecurity", "CEH / CISSP / CISA certification preferred", "Experience with SIEM tools, IDS/IPS, firewalls"],
    doc: "Notification_JOB2026015.pdf",
  },
  {
    id: "JOB-2026-014",
    title: "Network Engineer",
    titleHi: "नेटवर्क इंजीनियर",
    qualification: "B.Tech / CCNA / CCNP",
    experience: "2-4 years",
    lastDate: "2026-06-01",
    posts: 15,
    location: "Patna / Districts",
    salary: "₹ 35,000 – 55,000 / month",
    isNew: false,
    category: "Technical",
    description:
      "Design, configure, and maintain LAN/WAN network infrastructure for Bihar government departments and data centre interconnects.",
    eligibility: ["B.Tech (ECE/CS/IT) or Diploma with CCNA", "CCNP certification preferred", "Experience with Cisco/Juniper equipment"],
    doc: "Notification_JOB2026014.pdf",
  },
  {
    id: "JOB-2026-013",
    title: "Accounts Officer",
    titleHi: "लेखा अधिकारी",
    qualification: "CA / MBA Finance",
    experience: "5+ years",
    lastDate: "2026-05-25",
    posts: 3,
    location: "Patna (HQ)",
    salary: "₹ 60,000 – 95,000 / month",
    isNew: false,
    category: "Finance",
    description:
      "Handle financial accounting, budget preparation, audit compliance, and treasury management for BELTRON headquarters.",
    eligibility: ["CA / ICWA or MBA Finance from reputed institution", "5+ years in accounts/finance in PSU/government", "Knowledge of Tally, SAP, or government accounting systems"],
    doc: "Notification_JOB2026013.pdf",
  },
];
